name: build prod

on:
    workflow_dispatch:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
              id: buildx

            - name: Calculating the short git hash...
              run: echo "shorthash=$(echo ${{ github.sha }} | cut -c1-7)" >>$GITHUB_ENV #its imported from previous workflow

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  builder: ${{ steps.buildx.outputs.name }}
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.shorthash }}
